-- Eroi della community di Super YAC World: registro del consenso e limiti sull'archivio immagini.
--
-- Cosa fa:
--   1) crea la tabella PRIVATA public.avatars, dove api/save-avatar.js scrive (già oggi, ma la tabella
--      non esisteva e la scrittura falliva in silenzio) nick, email, nome dell'eroe, il TESTO della
--      casella accettata e la data: così, se qualcuno scrive «togliete il mio avatar», si ritrova il
--      suo eroe (join su path = profile_url) e si ha la prova di cosa ha accettato e quando;
--   2) chiude la tabella a anon/authenticated (RLS acceso, nessuna regola): ci scrive e legge solo il
--      server del gioco con la chiave di servizio;
--   3) mette sul bucket syw-heroes i limiti che il codice già impone (300 kB, solo image/png), così
--      valgono anche se un domani qualcuno carica da un'altra strada.
--
-- Perché: rilievi EXTRA1-2 (bucket senza limiti) ed EXTRA1-7 (consenso senza traccia, tabella mancante).
-- Non tocca heroes né i file già caricati. Se la chiave di servizio viene tolta da Vercel (EXTRA1-1),
-- la tabella resta semplicemente vuota.

create table if not exists public.avatars (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text,                 -- URL pubblico del ritratto (o dello sprite): lega la riga all'eroe in heroes
  hero_name text,
  nickname text,
  email text,
  power text,
  consent_social boolean not null default false,
  consent_text text          -- il testo esatto della casella spuntata
);

alter table public.avatars enable row level security;
revoke all on table public.avatars from anon, authenticated;

update storage.buckets
   set file_size_limit = 307200,            -- 300 kB
       allowed_mime_types = array['image/png']
 where id = 'syw-heroes';
